### ISSUE TITLE
numpy.core._internal.AxisError: axis 2 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by zxshi** [lRomul/argus-tgs-salt#1] opened 2018-11-12 09:04 UTC
**first**, I run make_inpaint_images.py, I get images148 and masks148;
**then**, I run train_folds.py from mos-fpn-lovase-se-resnext50-001, I get this **error**:
`2018-11-12 08:59:01,756 ERROR Traceback (most recent call last):
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/files/szx/argus-tgs-salt-master/src/dataset.py", line 57, in __getitem__
    input = self.depth_transform(image, depth)
  File "/media/files/szx/argus-tgs-salt-master/src/transforms.py", line 332, in __call__
    input = np.stack([image, image, image], axis=2)
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/numpy/core/shape_base.py", line 356, in stack
    axis = normalize_axis_index(axis, result_ndim)
numpy.core._internal.AxisError: axis 2 is out of bounds for array of dimension 1
Traceback (most recent call last):
  File "/media/files/szx/argus-tgs-salt-master/argus/engine/engine.py", line 69, in run
    for batch in data_loader:
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
numpy.core._internal.AxisError: Traceback (most recent call last):
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/files/szx/argus-tgs-salt-master/src/dataset.py", line 57, in __getitem__
    input = self.depth_transform(image, depth)
  File "/media/files/szx/argus-tgs-salt-master/src/transforms.py", line 332, in __call__
    input = np.stack([image, image, image], axis=2)
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/numpy/core/shape_base.py", line 356, in stack
    axis = normalize_axis_index(axis, result_ndim)
numpy.core._internal.AxisError: axis 2 is out of bounds for array of dimension 1

Traceback (most recent call last):
  File "train_folds.py", line 100, in <module>
    train_fold(save_fold_dir, train_folds, val_folds)
  File "train_folds.py", line 78, in train_fold
    metrics=['crop_iout'])
  File "/media/files/szx/argus-tgs-salt-master/argus/model/model.py", line 95, in fit
    self.validate(val_loader, metrics, val_callbacks)
  File "/media/files/szx/argus-tgs-salt-master/argus/model/model.py", line 154, in validate
    return val_engine.run(val_loader).metrics
  File "/media/files/szx/argus-tgs-salt-master/argus/engine/engine.py", line 86, in run
    raise e
  File "/media/files/szx/argus-tgs-salt-master/argus/engine/engine.py", line 69, in run
    for batch in data_loader:
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
numpy.core._internal.AxisError: Traceback (most recent call last):
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/media/files/szx/argus-tgs-salt-master/src/dataset.py", line 57, in __getitem__
    input = self.depth_transform(image, depth)
  File "/media/files/szx/argus-tgs-salt-master/src/transforms.py", line 332, in __call__
    input = np.stack([image, image, image], axis=2)
  File "/home/szx/Software/anaconda3/envs/torch-py3.7/lib/python3.7/site-packages/numpy/core/shape_base.py", line 356, in stack
    axis = normalize_axis_index(axis, result_ndim)
numpy.core._internal.AxisError: axis 2 is out of bounds for array of dimension 1
`
Can you give me some advice? Thank you very much!

**Comment by lRomul** [comment] 2018-11-13 23:03
Are you sure that generated all 4000 images? I added a check if an image and mask exists in [last commit](https://github.com/lRomul/argus-tgs-salt/commit/8dad52109484e481338ba0b8db840ba3dc7db42c).

**Comment by zxshi** [comment] 2018-11-14 03:04
yes, after I run **make_inpaint_images.py**, I get 4000 images in folder images148 and masks148.
But I noticed that TRAIN_FOLDS_PATH = **'data/train_folds_148_mos_emb_1.csv'** has been set in **train_folds.py**, and the file itself exists.
I guess running **make_inpaint_images.py** is useless, just run **train_folds.py** derectly.
what's your advice?

**Comment by lRomul** [comment] 2018-11-14 07:11
I think the problem is that in **train_folds_148_mos_emb_1.csv** there are absolute paths to images in docker environment. **cv2.imread** return **None** because the file does not exist in your anaconda environment. And **np.stack([None, None, None], axis=2)** failed with this error. 
Possible solutions:
* Use docker run instruction in readme.
* Replace folder path for each image in **train_folds_148_mos_emb_1.csv**.

**Comment by zxshi** [comment] 2018-11-14 13:03
OK, I will try your advice. Thank you very much!
In addition, I would like to ask how much GPU memory is needed？

**Comment by lRomul** [comment] 2018-11-14 18:57
Usually GPU memory consumption was around 8-9 GB.

**Comment by zxshi** [comment] 2018-11-15 01:54
I use SE-ResNeXt50(32*4d) as my backend, imageSize = 1024* 1024, bachsize = 4. Run them in 2080ti with 11G, I get CUDA_OUT_OF_MEMORY_ERROR. This makes me very confused.

**Comment by lRomul** [comment] 2018-11-15 07:05
With so large image size you can handle batch size 1, may be 2. 
This does not apply to this issue. I close it.

**Closed as completed by lRomul** 2018-11-15 07:05 UTC

**Comment by zxshi** [comment] 2018-11-16 01:01
OK, thank you very much!

**Comment by Aliktk** [comment] 2020-02-04 05:36
runfile('C:/Users/Ali ktk/.spyder-py3/AD_Prediction-master new/AD_Prediction-master/main_alexnet.py', wdir='C:/Users/Ali ktk/.spyder-py3/AD_Prediction-master new/AD_Prediction-master')
Reloaded modules: custom_transform2D, AD_Dataset, AD_Standard_2DSlicesData, AD_Standard_2DRandomSlicesData, AD_Standard_2DTestingSlices, AlexNet2D
2020-02-04 10:23:12 INFO: At 0-th epoch.
Traceback (most recent call last):

  File "<ipython-input-19-75535f1f7ad6>", line 1, in <module>
    runfile('C:/Users/Ali ktk/.spyder-py3/AD_Prediction-master new/AD_Prediction-master/main_alexnet.py', wdir='C:/Users/Ali ktk/.spyder-py3/AD_Prediction-master new/AD_Prediction-master')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Ali ktk/.spyder-py3/AD_Prediction-master new/AD_Prediction-master/main_alexnet.py", line 238, in <module>
    main(options)

  File "C:/Users/Ali ktk/.spyder-py3/AD_Prediction-master new/AD_Prediction-master/main_alexnet.py", line 134, in main
    train_loss, correct_cnt = train(model, train_loader, use_cuda, criterion, optimizer, train_loss_f)

  File "C:/Users/Ali ktk/.spyder-py3/AD_Prediction-master new/AD_Prediction-master/main_alexnet.py", line 162, in train
    for it, train_data in enumerate(train_loader):

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]

  File "C:\Users\Ali ktk\.spyder-py3\AD_Prediction-master new\AD_Prediction-master\AD_Standard_2DRandomSlicesData.py", line 53, in __getitem__
    AXimageList = axRandomSlice(image)

  File "C:\Users\Ali ktk\.spyder-py3\AD_Prediction-master new\AD_Prediction-master\AD_Standard_2DRandomSlicesData.py", line 87, in axRandomSlice
    return getRandomSlice(image_array, AX_INDEX, AX_SCETION)

  File "C:\Users\Ali ktk\.spyder-py3\AD_Prediction-master new\AD_Prediction-master\AD_Standard_2DRandomSlicesData.py", line 81, in getRandomSlice
    slice_2Dimg = np.stack((slice_select_0, slice_select_1, slice_select_2), axis = 2)

  **File "C:\ProgramData\Anaconda3\lib\site-packages\numpy\core\shape_base.py", line 419, in stack
    axis = normalize_axis_index(axis, result_ndim)

AxisError: axis 2 is out of bounds for array of dimension 1**
I am working on MRI images where i get this error by using this [https://github.com/wangyirui/AD_Prediction] code.
In that repo no one having this type of error but I am getting this error after removing multiple errors 
please give me suggestion
